version: 2.1

orbs:
  ruby: circleci/ruby@2.3.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.10
    steps:
      - checkout
      # Add step below to install Ruby version 2.6.3
      - ruby/install:
          version: '2.6.3'
      - run: ruby -v

workflows:
  run-jobs:
    jobs:
      - build
