version: 2.1

jobs:
  build:
    docker:
      - image: cimg/postgres:17.0
        environment:
          POSTGRES_USER: postgres
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: whoami
      - run: |
          psql \
          -d "postgresql://postgres@localhost/circle_test" \
          -c "CREATE TABLE test (name char(25));"
      - run: |
          psql \
          -d "postgresql://postgres@localhost/circle_test" \
          -c "INSERT INTO test VALUES ('John'), ('Joanna'), ('Jennifer');"

workflows:
  build-workflow:
    jobs:
      - build